### ISSUE TITLE
Build flow & Architect with 5w1h 

### ISSUE THREAD

**Issue by tofulim** [tofulim/auto_trade#1]
### what
매월 특정 날짜마다 정해놓은 일정 금액을 주식에 투자하고자 한다. 
이를 python 활용한 자동매매로 구현하는 프로젝트
기본적으로 long 포지션을 잡고 나는 이 주식들을 잊고 현생을 잘 살아가는 게 목표

public repo기 때문에 기타 credential을 env나 config로 만든 뒤 .gitignore하고 private하게 관리해야함

### why
머신러닝 forcast류 모델과 주식 도메인을 결합한 프로젝트를 통해 airflow를 익히고 작은 재테크도 하기 위함
주식에 대한 관심과 기술적 호기심을 둘 다 해결할 수 있는 프로젝트 

### how
월급 다음날 내 월급의 10%를 정해진 n개의 종목에 투자한다. (이 때 비율은 사전에 정의한다.)

예측에 사용할 모델은 ARIMA를 활용하며 추후 가벼운 DL 모델로 변경될 수 있음.
-> meta prophet 이용
구동 서버는 (AWS free tier | firebase ) 활용한다. 그렇기에 무거운 모델 사용 불가

단, 몇 가지 개발 요구사항이 있다.
- 자동으로 종목을 판매하는 경우는 미리 정의된 최악의 케이스뿐이어야 한다. (ex. 반토막난 경우)
- 백트레킹 및 더미 종목 투자가 가능하도록 개발되면 좋겠음.
  - '아 이거 투자해보면 좋을거같은데~' 싶은 종목들을 가상으로 투자할 수 있도록
- 구매조건을 만족하지 않으면 해당 월의 할당 금액을 사용하지 않고 다음달로 이월됨.
  - 구매조건 전략에 대한 정의가 필요함

### when
- 월급날 5일의 익일부터 익월까지 종목당 매월 0번 혹은 1번의 구매가 이루어짐
- > 매수 횟수를 1회 이상 m번으로 확장하여 분할매수하는 것도 방법 (증가예측률이 내가 지정한 n%를 초과하는 m회마다 매수)

### RoadMap
- [x] 의사결정도구 prophet 코드 개발 (#10)
- [x] 한투 API 활용한 Trader 코드 개발 (#2)
- [x] FastAPI 서버 개발 (#13)
- [x] Database (sqlite) 추가 (#16)
- [x] airflow 배치 프로세스 개발 (#15)
- [x] Slack 연동 (#3)
- [x] CI/CD (#75)

### Architecture
<img width="815" alt="image" src="https://github.com/tofulim/auto_trade/assets/52443401/51e3669c-6fd6-4585-b043-f77586f0236d">

**Comment by tofulim** [comment]
<img width="1481" alt="image" src="https://github.com/tofulim/auto_trade/assets/52443401/36aa04fe-6f4b-431f-9eff-3c5c39b80958">

**Comment by tofulim** [comment]
그림도 수정이 필요함 prophet도 slack으로 알람 보냄

**Comment by tofulim** [comment]
ec2 free tier인 t2.micro에서 Apache Airflow를 돌리려면 옵션 조절이 필요하다. (프로세스워커, 스레드, 갱신 인터벌 조절)
안그럼 인스턴스가 죽어버린다. cpu 스파크 튀어 stuck 걸려 중지하고 재시작해야함..

설정해야하는 옵션은 다음과 같다.
- AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL=90
- AIRFLOW__WEBSERVER__WORKERS=1

참조한 정보 
https://stackoverflow.com/questions/42419834/airbnb-airflow-using-all-system-resources

**Comment by tofulim** [comment]
웹 ui에서 dag 하나를 활성화하면 갑자기 cpu가 치솟는다
<img width="834" alt="image" src="https://github.com/user-attachments/assets/a581cb11-08b2-428d-9da1-027fcc4a183d">

**Comment by tofulim** [comment]
prophesy and decision dag에서 utc로 돼있어서 

# 매일 08:25 시간 외 장전거래를 실행합니다 (08:20 - 08:40)
    schedule_interval="25 8 * * *",

이 라인에서 실행하는데 아침이 아닌 오후 17:25에 예측 및 슬랙 알람이 옴
![image](https://github.com/user-attachments/assets/87e53206-100b-4b89-bac3-d096fc0f6597)
